version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: planoria-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Planoria123*
    ports:
      - "1433:1433"
    networks:
      - planoria-network

  backend:
    build: .
    container_name: planoria-backend
    ports:
      - "7075:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PlanoriaDatabase;User Id=sa;Password=Planoria123*;TrustServerCertificate=True;
      - GEMINI_API_KEY=AIzaSyC2_G6CpoXF9bA2B9zDzI81JWVtHDXx350
    networks:
      - planoria-network

networks:
  planoria-network: