// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanoriaCapstone.Dal;

#nullable disable

namespace PlanoriaCapstone.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanoriaCapstone.Models.AnalisisIA", b =>
                {
                    b.Property<int>("IdAnalisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnalisis"));

                    b.Property<string>("EstadoProceso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PROCESANDO");

                    b.Property<DateTime>("FechaAnalisis")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArchivo")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemasDetectados")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnalisis");

                    b.HasIndex("IdArchivo");

                    b.ToTable("AnalisisIA");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.ArchivoSubido", b =>
                {
                    b.Property<int>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArchivo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TamanoMB")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdArchivo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ArchivosSubidos");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.EstadisticaIA", b =>
                {
                    b.Property<int>("IdEstadistica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadistica"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal?>("PromedioPuntaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalArchivosSubidos")
                        .HasColumnType("int");

                    b.Property<int>("TotalFlashcardsGeneradas")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuizzesGenerados")
                        .HasColumnType("int");

                    b.HasKey("IdEstadistica");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("EstadisticasIA");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Flashcard", b =>
                {
                    b.Property<int>("IdFlashcard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlashcard"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("int");

                    b.Property<string>("NivelDificultad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VecesEstudiada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdFlashcard");

                    b.HasIndex("IdAnalisis");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.HistorialFlashcard", b =>
                {
                    b.Property<int>("IdHistorialFlashcard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialFlashcard"));

                    b.Property<bool>("Correcta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFlashcard")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoRespuestaSegundos")
                        .HasColumnType("int");

                    b.HasKey("IdHistorialFlashcard");

                    b.HasIndex("IdFlashcard");

                    b.HasIndex("IdUsuario");

                    b.ToTable("HistorialFlashcards");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.HistorialQuiz", b =>
                {
                    b.Property<int>("IdHistorialQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialQuiz"));

                    b.Property<int>("CantidadCorrectas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadIncorrectas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdQuiz")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Puntaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TiempoResolucionMinutos")
                        .HasColumnType("int");

                    b.HasKey("IdHistorialQuiz");

                    b.HasIndex("IdQuiz");

                    b.HasIndex("IdUsuario");

                    b.ToTable("HistorialQuizzes");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.PreguntaQuiz", b =>
                {
                    b.Property<int>("IdPreguntaQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPreguntaQuiz"));

                    b.Property<string>("Explicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdQuiz")
                        .HasColumnType("int");

                    b.Property<string>("OpcionA")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OpcionB")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OpcionC")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OpcionD")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaCorrecta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPreguntaQuiz");

                    b.HasIndex("IdQuiz");

                    b.ToTable("PreguntasQuiz");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.ProgresoArchivo", b =>
                {
                    b.Property<int>("IdProgresoArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgresoArchivo"));

                    b.Property<bool>("Completado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("FlashcardsCompletadas")
                        .HasColumnType("int");

                    b.Property<int>("FlashcardsTotales")
                        .HasColumnType("int");

                    b.Property<int>("IdArchivo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeProgreso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuizzesCompletados")
                        .HasColumnType("int");

                    b.Property<int>("QuizzesTotales")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaSesion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProgresoArchivo");

                    b.HasIndex("IdArchivo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ProgresoArchivos");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Quiz", b =>
                {
                    b.Property<int>("IdQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuiz"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdQuiz");

                    b.HasIndex("IdAnalisis");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.RachaUsuario", b =>
                {
                    b.Property<int>("IdRacha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRacha"));

                    b.Property<int>("DiasConsecutivos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdRacha");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RachasUsuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "ADMIN"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "USER"
                        });
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("LOCAL");

                    b.Property<int>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RachaDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.AnalisisIA", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.ArchivoSubido", "ArchivoSubido")
                        .WithMany("AnalisisIA")
                        .HasForeignKey("IdArchivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivoSubido");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.ArchivoSubido", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Usuario", "Usuario")
                        .WithMany("ArchivosSubidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Auditoria", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.EstadisticaIA", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Usuario", "Usuario")
                        .WithOne("EstadisticaIA")
                        .HasForeignKey("PlanoriaCapstone.Models.EstadisticaIA", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Flashcard", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.AnalisisIA", "AnalisisIA")
                        .WithMany("Flashcards")
                        .HasForeignKey("IdAnalisis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalisisIA");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.HistorialFlashcard", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Flashcard", "Flashcard")
                        .WithMany("HistorialFlashcards")
                        .HasForeignKey("IdFlashcard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanoriaCapstone.Models.Usuario", "Usuario")
                        .WithMany("HistorialFlashcards")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.HistorialQuiz", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Quiz", "Quiz")
                        .WithMany("HistorialQuizzes")
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanoriaCapstone.Models.Usuario", "Usuario")
                        .WithMany("HistorialQuizzes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.PreguntaQuiz", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Quiz", "Quiz")
                        .WithMany("PreguntasQuiz")
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.ProgresoArchivo", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.ArchivoSubido", "ArchivoSubido")
                        .WithMany()
                        .HasForeignKey("IdArchivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanoriaCapstone.Models.Usuario", "Usuario")
                        .WithMany("ProgresoArchivos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ArchivoSubido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Quiz", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.AnalisisIA", "AnalisisIA")
                        .WithMany("Quizzes")
                        .HasForeignKey("IdAnalisis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalisisIA");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.RachaUsuario", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Usuario", "Usuario")
                        .WithMany("RachasUsuario")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Usuario", b =>
                {
                    b.HasOne("PlanoriaCapstone.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.AnalisisIA", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.ArchivoSubido", b =>
                {
                    b.Navigation("AnalisisIA");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Flashcard", b =>
                {
                    b.Navigation("HistorialFlashcards");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Quiz", b =>
                {
                    b.Navigation("HistorialQuizzes");

                    b.Navigation("PreguntasQuiz");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PlanoriaCapstone.Models.Usuario", b =>
                {
                    b.Navigation("ArchivosSubidos");

                    b.Navigation("Auditorias");

                    b.Navigation("EstadisticaIA");

                    b.Navigation("HistorialFlashcards");

                    b.Navigation("HistorialQuizzes");

                    b.Navigation("ProgresoArchivos");

                    b.Navigation("RachasUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
